Dev container
Qulacs-Osaka/scikit-qulacs pull request #119
Opened 2021-12-16 09:00 UTC by ikanago

最低限の dev-container の設定をしました．
まだ開発に使うにあたって不足があるかもしれないのでいろいろ試してみてもらえるとありがたいです．

## 使い方
1. Docker を用意する
2. VSCode に [Remote Container](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) をインストールする
3. このリポジトリの dev-container ブランチをチェックアウトする
4. コマンドパレットから "Reopen in Container" を入力する

2021-12-17 06:39 UTC, KowerKoint requested changes
`poetry config virtualenvs.in-project true` を先に実行するのを忘れて無駄な仮想環境が作られてしまうことがあるので、
`poetry config virtualenvs.in-project true --local` で生成された `poetry.toml` を初めから加えると良いと思うのですが、どうでしょう

2021-12-17 06:41 UTC, KowerKoint commented
それ以外には大変使いやすくていい感じでした！

2021-12-17 07:07 UTC, KowerKoint commented on .devcontainer/devcontainer.json
> +		"python.linting.pylintEnabled": true,
```suggestion
		"python.linting.pylintEnabled": false,
```
pylintがImport Errorを起こすのでfalseにしたほうが良さそうです。
これをfalseにしても本当に存在しないimportに対する注意は正常に出ることを確認しています。

2021-12-17 08:01 UTC, Hiroya-W requested changes
dev-container使ってみました！ほとんどVSCodeがやってくれるので便利だなと感じています。後は、python-project-templateと合わせて使えるような設定ができれば良さそうです。

2021-12-17 08:01 UTC, Hiroya-W commented on .devcontainer/devcontainer.json
> +		"python.linting.pylintEnabled": true,
poetry で環境を作るので、コンテナ内に用意されているPythonやツールを使う必要も無さそうです。VSCodeでPythonインタープリタを指定すれば、poetryでインストールしたblackやflake8にパスが通るはずです。

また、KowerKointさんも指摘していますが、pylintを無効にしてflake8を有効にする、blackやisort、mypyの設定は最低限必要かと思っています。ここは、python-project-templateで使っているツールに合わせておくといいと思っています。

```json
	"settings": {
		"python.defaultInterpreterPath": "${containerWorkspaceFolder}/.venv/bin/python",
		"python.linting.enabled": true,
		"python.linting.pylintEnabled": false,
		"python.linting.flake8Enabled": true,
		"python.formatting.provider": "black",
		"editor.formatOnSave": true,
		"editor.codeActionsOnSave": {
			"source.organizeImports": true
		},
		"python.linting.mypyEnabled": true,
	},
```

2021-12-17 08:04 UTC, Hiroya-W commented
また、気になったことをいくつか共有しておきます。

- dev-containerを使う前に作成していた `.venv`は削除しておかないと、poetryが自動的に使おうとしてしてエラーになる（ホスト環境のmacOS用の仮想環境になっていたのでDockerコンテナ内では使えなかった）
    - Docker環境で作った仮想環境をホスト側で使おうとする場面もありえそうです。
- Windows, macOSだとDockerのbind mountではディスクの書き込みが遅いことが知られていると思うので、対策がいずれ必要になると思います。1回ずつの計測なので正確ではない可能性がありますが、自分のintel macOSでの参考程度の結果です。

```
$ poetry config virtualenvs.in-project true
$ time poetry install

real    15m51.185s
user    7m29.417s
sys     2m25.251s

$ poetry config virtualenvs.in-project false
$ time poetry install

real    5m44.282s
user    6m23.704s
sys     1m10.202s
```

- 同じ問題として、`node_modules`で起きる話が書いてあります。少し複雑になってしまいますが、今後はNamedVolumeを作ってVolumeマウントを使うことも議論したいです。
    - https://code.visualstudio.com/remote/advancedcontainers/improve-performance
- 名前が重複しない用に、プロジェクト名-venvでVolumeを作成して、マウントするのはこのように出来ると思います。

```json
    // devcontainer.json
	"mounts": [
		"source=${localWorkspaceFolderBasename}-venv,target=${containerWorkspaceFolder}/.venv,type=volume"
	],
	"postStartCommand": "/usr/bin/git config --global gpg.program /usr/bin/gpg && sudo chown vscode .venv",
```

- ホスト環境の`.gitconfig`もコンテナ内にコピーしてくれるのはありがたいのですが、個人的にdiffを他のツールに置き換えたり、git-secretsを使っていたりすると、そのままでは使えないみたいでした。個人的な問題なので、個人で修正しようと思います。

2021-12-17 08:35 UTC, kotamanegi approved these changes
上記の内容を反映した上であればLGTMです！

2021-12-21 04:52 UTC, ikanago commented
> `poetry config virtualenvs.in-project true --local` で生成された `poetry.toml` を初めから加えると良いと思うのですが

加えておきました!  このファイルがあれば起動時にコマンドを実行しなくてもその設定が有効になっていることを確認できました．

2021-12-21 04:58 UTC, ikanago commented
> * dev-containerを使う前に作成していた `.venv`は削除しておかないと、poetryが自動的に使おうとしてしてエラーになる

使い方をドキュメントにまとめるときに書くようにします．

> 今後はNamedVolumeを作ってVolumeマウントを使うことも議論したいです

試してみます．

> ホスト環境の.gitconfigもコンテナ内にコピーしてくれるのはありがたいのですが、個人的にdiffを他のツールに置き換えたり、git-secretsを使っていたりすると、そのままでは使えないみたいでした

僕も diff を git-delta にしているのでどうにかしたいなと思っています 👀

2021-12-22 00:32 UTC, KowerKoint approved these changes
LGTMです！

2021-12-22 00:34 UTC, KowerKoint commented
mypyのlintにたくさん引っかかるのでこれを通過できるように型アノテーションを書いていく必要がありそうですね…

2021-12-22 01:38 UTC, kotamanegi approved these changes
LGTMです！
変な.venvがある状態でdevcontainerを開くと、その後どうやってもpoetryがエラーで落ちてしまってコンテナごとrebuildするしかなくなるということを書いていただけると嬉しいです。

2021-12-23 05:03 UTC, ikanago commented
僕の環境では .env が残ってても volume mount なら問題なかったんですが，ややこしいので分かる人以外はそうしたほうがいいですね．書いておきます．

2021-12-23 05:03 UTC, merged