Remove --no-root to install skqulacs to venv for doc build
Qulacs-Osaka/scikit-qulacs pull request #133
Opened 2022-02-08 07:53 UTC by ikanago

2022-02-08 08:23 UTC, Hiroya-W requested changes
PRありがとうございます、自分も見落としていました…。
確かに、 `--no-root`があると、 scikti-qulacs 本体はインストールされないので、この修正が必要そうです。
GitHub Actions上でキャッシュされた venv が、scikit-qulacs がインストールされた状態でキャッシュされているのが原因な感じかも、と思いました。

2022-02-08 08:23 UTC, Hiroya-W commented on .github/workflows/doc.yml
> +        run: poetry install --no-interaction
この書き方だと、`poetry.lock`が変更された時のみインストールが実行されるので、scikit-qulacs本体のソースコードの変更が反映されない気がします。
[unittestのworkflow](https://github.com/Qulacs-Osaka/scikit-qulacs/blob/main/.github/workflows/unittest.yml)のように、Install dependenciesのステップの後、Install libraryのステップを追加するのがいいかもしれません。

```yml
    - name: Install dependencies
      if: steps.cached-poetry-deps.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root

    - name: Install library
      run: poetry install --no-interaction
```

2022-02-10 06:37 UTC, ikanago commented on .github/workflows/doc.yml
> +        run: poetry install --no-interaction
たしかにそうすべきですね，ありがとうございます

2022-02-10 06:42 UTC, ikanago commented
レビューありがとうございました!  見落としに気づけたので助かりました．

2022-02-15 07:20 UTC, Hiroya-W approved these changes
LGTM!

2022-02-17 05:01 UTC, merged