use_scikit_prepro
Qulacs-Osaka/scikit-qulacs pull request #149
Opened 2022-03-11 06:38 UTC by WATLE

scikitのpreprossessingを使った。
ついでに、classにもx_norm_rangeの項目を追加(regにはあった)

2022-03-11 06:38 UTC, WATLE commented
#140

2022-03-15 07:04 UTC, ikanago commented on skqulacs/qnn/classifier.py
>      def rev_y_scale(self, y_inr):
このメソッドは `np.argmax` で簡単に書けそうです．
例えば以下のようになります(テストしてないのでうまく動くかは分からないです)．
```python
def inverse_one_hot(y_pred: np.array):
    # Convert probability to one-hot encoding
    class_indices = y_pred.argmax(axis=1)
    y_one_hot = np.identity(y_pred.shape[1])[class_indices]
    return self.enc.inverse_transform(y_one_hot)
```
参考: https://note.nkmk.me/python-numpy-eye-identity-one-hot/

2022-03-15 07:29 UTC, ikanago commented on skqulacs/qnn/regressor.py
> +                feature_range=(-self.y_norm_range, self.y_norm_range)
`feature_range` を `(-1, 1)` にしているのは `arcsin` に渡すからですね，思い出しました

2022-03-18 04:44 UTC, WATLE commented on skqulacs/qnn/classifier.py
> +        # scikitのone-hotを使っても、　種類ごとにmaxの要素を検出してくれるわけではないので、ここはそのままです。
英語でコメントすると自分で見れないのでどうしましょう...

2022-03-18 04:54 UTC, WATLE commented on skqulacs/qnn/regressor.py
> +                feature_range=(-self.y_norm_range, self.y_norm_range)
Y_NORM_RANGE=0.7のほうが性能が良いはず

2022-03-18 05:01 UTC, WATLE commented on skqulacs/qnn/classifier.py
>      def rev_y_scale(self, y_inr):
classifier,一つのQNNで同時に複数個の分類ができます
例えば、[入力データ１] = [犬,オス]  、　[入力データ2] = [猫、メス]  [入力データ3] = [猫、オス]
のように。
これはscikitにあるという理由で実装し、あまり使わないのでろくにテストもされていないが、後方互換性のために消すわけにもいかず、実装を複雑化させています。
この問題に関しては別のIssueを建てます。

2022-03-18 05:03 UTC, WATLE commented on skqulacs/qnn/classifier.py
>      def rev_y_scale(self, y_inr):
#151

2022-03-23 05:48 UTC, ikanago commented on skqulacs/qnn/regressor.py
> +                feature_range=(-self.y_norm_range, self.y_norm_range)
じゃあコンストラクタに "Setting `y_norm_range` to 0.7 improves performance." みたいなことを書いとくとよさそうです．

2022-03-23 08:18 UTC, WATLE commented on skqulacs/qnn/classifier.py
>      def rev_y_scale(self, y_inr):
一つのQNNで同時に複数個の分類の分類をやめることにより、np.argmaxを採用します。

2022-03-23 09:28 UTC, WATLE commented
logloss-fixの内容もこれに含まれています

2022-03-23 09:29 UTC, WATLE commented
ちなみに、one-fotいらなくなりました

2022-03-24 05:52 UTC, ikanago requested changes
scikit-learn にあるモジュールを使うとかなりすっきりしたと思います．
いくつかコメントしたので確認お願いします 🙏

2022-03-24 05:52 UTC, ikanago commented on skqulacs/qnn/regressor.py
> +            )
かなりシンプルになっていいと思います．

2022-03-24 05:52 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +            return log_loss(y_scaled, y_pred_sm)
scikit-learn にあるやつで済むならそのほうがよさそうですね．

2022-03-24 05:52 UTC, ikanago commented on skqulacs/qnn/classifier.py
>          for h in range(len(x_scaled)):
`h` よりも `sample_index` とか `current_sample` のように，「何番目のデータを見ている」という意味を込めたほうが読みやすくなると思いました．

2022-03-24 05:52 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +            for i in range(self.num_class):
ここの `i` も同様に，`dim` とか `current_class` のように「あるデータの何番目の値を見ている」という意味を込めると読みやすいです．

2022-03-24 05:52 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +                aaa = 0.0
`y_pred_sm[h][i] - aaa` が `0.0` に近いとき `aaa` を `1.0` にしているので，`aaa` よりは `expected` とかのほうが適していそうです．

2022-03-24 05:52 UTC, ikanago commented on tests/test_qnn_classifier.py
>          y_pred = qcl.predict(x_test)
この部分なんですが，古いブランチから checkout しているのか修正されていないので
```python
qcl.fit(x_train, y_train, maxiter)
y_pred = qcl.predict(x_test)
```
としておいてください．

2022-03-24 05:52 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +            for j in range(self.num_class):
observable は `self.n_qubit` 個あるのに対して `self.num_class` がこれと異なる場合は範囲外参照になったり冗長になったりします．
なので内側のループは `range(self.n_qubit)` のままでよくて，前の実装のままでよさそうです．

2022-03-24 05:52 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +            for j in range(self.num_class):
そもそもなんですが，たとえば `num_class=3`，`n_qubits=4` で学習すると，ある `i` について `y_pred[i]` が `[0.1, 0.0, 0.1, 0.8]` みたいになることがありえて，これは不正解になるので `num_class == n_qubits` とすべきである気がします．この場合 `num_class` を用意する必要はないです．

2022-03-25 04:14 UTC, WATLE commented on skqulacs/qnn/classifier.py
> +            for j in range(self.num_class):
num_class == n_qubitsとしたとき、2値分類するときにnum_class =2となりますが、それだと量子2ビットの回路しか使えなくなります。そうすると、回路の複雑性が不足します。

よって、num_class と n_qubitsを別にして、　番号が大きいビットは観測しないことにしています。

num_class <= n_qubits である必要があることは書くべきかもしれません。

2022-03-29 04:17 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +            for j in range(self.num_class):
> 回路の複雑性が不足します

なるほど，そういうことだったんですね

このことと `num_class <= n_qubits` の必要性は明記しておいたほうがたしかに親切だと思います．

2022-03-29 04:18 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +            for j in range(self.num_class):
もう書いてありましたね，ありがとうございます

2022-03-29 04:19 UTC, ikanago approved these changes
LGTM です!

2022-04-12 06:57 UTC, WATLE commented
QCNN関係が手元でテスト通らないんだけどどうしよう

2022-04-12 07:00 UTC, ikanago commented
140-use-scikit-prepro の最新のコミットで `make test` すると僕の手元では通りました

2022-04-12 07:26 UTC, ikanago commented
フォーマットで CI 落ちてるので make fix したらマージできそうですね

2022-04-12 07:36 UTC, ikanago commented
通りましたね

2022-04-12 07:44 UTC, merged