early_stopping
Qulacs-Osaka/scikit-qulacs pull request #154
Opened 2022-03-23 10:40 UTC by WATLE

#144

2022-03-29 05:10 UTC, ikanago requested changes

2022-03-29 05:10 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +                if (self.n_iter_no_change < 999999) and (iter % len(x_scaled) < 5):
`self.n_iter_no_change < 999999` の部分ですが，これは `self.n_iter_no_change` が `999999` 以上のときは early stopping を無効にするということですか?
`self.n_iter_no_change` を `Optional[int]` (デフォルトは `None`)にして `self.n_iter_no_change != None` のときは early stopping の判定をするようにしたほうがわかりやすそうですがどうでしょうか．

2022-03-29 05:10 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +            nochan = 0
`n_iter_no_change` では `no` のあとに `_` を入れているので `no_change` とか `no_change_iter` とかにしたほうがわかりやすそうです．

2022-03-30 08:07 UTC, WATLE commented on skqulacs/qnn/classifier.py
> +            nochan = 0
scikitがn_iter_no_change　という名前なので、そうしました

2022-03-30 08:10 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +            nochan = 0
これはっきり書いてませんでしたね，`nochan` に対する言及でした

2022-03-30 08:14 UTC, WATLE commented on skqulacs/qnn/classifier.py
> +                if (self.n_iter_no_change < 999999) and (iter % len(x_scaled) < 5):
確かにそうですね、
一応、self.n_iter_no_changeが非常に大きい場合、実質的にこの機能は無効になるという理由でデフォルトが999999にはなっています。

2022-04-07 07:22 UTC, merged