Share learning parameters
Qulacs-Osaka/scikit-qulacs pull request #166
Opened 2022-03-30 07:31 UTC by ikanago

close #141 
ひとつの `_LearningParameter` を介して `ParametricQuantumCircuit` 内の複数のパラメータを制御できるようになりました．

@WATLE backprop の部分は，各 `_LearningParameter` が共有している `ParametricQuantumCircuit` の backprop を足し合わせるように実装したんですが，これで問題なさそうか確認お願いします．

2022-03-30 08:25 UTC, WATLE requested changes
シンプルなミスです

2022-03-30 08:25 UTC, WATLE commented on skqulacs/circuit/circuit.py
> +            index: Index of qubit to add RX gate.
RZゲートです

2022-03-30 08:25 UTC, WATLE commented on skqulacs/circuit/circuit.py
> +            index: Index of qubit to add RX gate.
RYゲートです

2022-03-30 08:26 UTC, WATLE commented
あまり詳しくは見れていませんが、　backpropは足し合わせる実装で正解です。

2022-04-07 06:20 UTC, WATLE approved these changes

2022-04-07 06:38 UTC, kosukemtr approved these changes
いいと思います！次はシェアされているパラメータに係数がかかってるみたいなのもできるといいかもしれないですー。( -RX(2*θ_1)-RZ(θ_2)-RX(0.5*θ_1)- みたいな回路を作りたいときもあるかもしれないので)

2022-04-07 06:42 UTC, ikanago commented
了解です!
とりあえず issue にしておきました: #169

2022-04-07 06:43 UTC, merged