Add visualization of pre-defined circuits on tutorials
Qulacs-Osaka/scikit-qulacs pull request #178
Opened 2022-04-18 00:46 UTC by herring101

close #83 
`pre-defined.py`にある量子回路の可視化をtutorialに追加しました。
qcl_ansatzのみコードを記載し、それほかの量子回路は画像のみ載せています。
そのほかの量子回路を可視化したコードは`circuit_visualize.ipynb`にあります。

気になった点
- qcnn_ansatzの量子回路が大きくなってしまうため見えづらい
- `用意されている量子回路`という章で紹介されている量子回路は古いversionのscikit-qulacsのものであるため、そちらの更新も必要

2022-04-19 04:22 UTC, ikanago requested changes
circuit_visualize.ipynb が1つのページとして生成されていないので，`doc/source/notebooks/index.rst` に `circuit_visualize` を追加しておいてください．
`make serve` して `localhost:8000` にアクセスするとビルドしたドキュメントを確認できます．

あと画像はすべて `doc/source/notebooks/figures` に置きたいので，`doc/source/notebooks/figures/circuit_visualize` みたいな名前のディレクトリを切ってそこに画像を入れておいてください 🙏

2022-04-19 05:50 UTC, Hiroya-W approved these changes
PRありがとうございます！どんな量子回路なのかは描画出来ると分かりやすくなりますね！
qulacsvis、使えそうだけど惜しいところが気になりますね。使い方や描画に関してはLGTMです！

描画結果で、ゲートを左詰めできる部分は出来るように今修正してくれているところで、これが出来ればqcnn_ansatzは特にコンパクトに表示出来るようなりそうです。
shirai_ansatzに関しては、あまり短くはならないので、途中で折り返して表示するような描画方法が必要になるのかなぁと思っています。現状だとこれより良い描画方法はqulacsvisには無いのですが、ブラウザなどでは、別タブで画像だけ開いて表示すれば、一応拡大して見ることが出来ますね。

ゲート名のテキストの読みやすさはLaTeXでの描画が分かりやすいし、matplotlibでの描画での調整をqulacsvisで対応しようと思います。

2022-04-19 06:06 UTC, kosukemtr commented
ありがとうございます。0_tutorial にすべての回路を載せるのは少し可読性を低下させる気がするので、代表的な ansatz として ibmq_embedding_circuit と farhi_neven_ansatz の２つだけを載せていただけるでしょうか？
その上で、circuit_visualize.ipynb へのリンクを貼って、「他に利用可能な量子回路のリストについてはこのページを見てください」のようにできると嬉しいです。さらに、そういう変更をしてユーザーに見られるという前提で、circuit_visualize.ipynb も少し内容を (コードブロックだけでなくてテキストブロックに論文のリンクを貼るなどして) 充実させて頂きたいです。

2022-04-19 06:58 UTC, WATLE reviewed
farhi_neven_anstazとfarhi_neven_watle_anstazは回路としては同じ
回転角が違っていて、同じパラメータが複数のゲートに影響するとき、watle側はパラメータの高い側に反応するゲートと低い側に反応するゲートに分ける
元のは同じ回転角が複数のゲートに行く

だから、図としては同じはず　でも、(両方の)farhiは回路として乱数を使うから、その差で回路が違うだけ

2022-04-19 07:00 UTC, WATLE approved these changes

2022-04-20 09:04 UTC, herring101 commented
いくつか修正を加えました。
- 画像ファイルのディレクトリを変更
- `量子回路の可視化`という章は削除
- tutorialには`farhi_neven_ansatz`, `ibm_embedding_circuit`のみを紹介し、その下にqulacs-visualizerを用いて生成した量子回路の画像を置いた
- `circuit_visualize.ipynb`に論文へのリンクなどを追加。

2022-04-21 04:17 UTC, ikanago requested changes

2022-04-21 04:17 UTC, ikanago commented on pyproject.toml
> +qulacsvis = "^0.2.1"
poetry の dependencies にはアプリやライブラリの動作に必要なパッケージを，dev-dependencies には開発のときのみ必要なパッケージを書きます．
`qulacsvis` は開発のときのみ必要なので，dev-dependencies に書いてください．
```bash
poetry remove qulacsvis  # 一旦削除する
poetry add -D qulacsvis  # dev-dependencies としてインストール
```

2022-04-21 04:17 UTC, ikanago commented on doc/source/notebooks/index.rst
> +   circuit_visualize
👍

2022-04-21 04:17 UTC, ikanago commented on doc/source/notebooks/circuit_visualize.ipynb
> +    "このドキュメントでは scikit-qulacs に用意されている量子回路の可視化します。\n",
些細ですが「量子回路の可視化をします」ですね

2022-04-21 05:00 UTC, herring101 commented on pyproject.toml
> +qulacsvis = "^0.2.1"
開発者用の依存パッケージの存在を忘れていました...

それならcircuit_visualize.ipynbに
```pip install qulacsvis```でqulacs-visualizerをインストールしましょうということを書いた方が親切でしょうか？

2022-04-21 05:02 UTC, ikanago commented on pyproject.toml
> +qulacsvis = "^0.2.1"
たしかにそうですね，どうやって可視化したか分からないのでインストールすることを明記した方がいいと思います．

2022-04-21 05:18 UTC, herring101 commented on doc/source/notebooks/index.rst
> +   circuit_visualize
こんなに簡単にページを作れるのは便利ですね！驚きました

2022-04-21 05:18 UTC, herring101 commented on doc/source/notebooks/circuit_visualize.ipynb
> +    "このドキュメントでは scikit-qulacs に用意されている量子回路の可視化します。\n",
修正しました

2022-04-21 05:20 UTC, ikanago approved these changes

2022-04-21 07:22 UTC, ikanago commented
マージしちゃっていいと思います

2022-04-21 07:23 UTC, merged