#169: 共有されているパラメータに係数をかけられるようにする
Qulacs-Osaka/scikit-qulacs pull request #195
Opened 2022-05-27 05:07 UTC by forest1040

2022-06-14 05:03 UTC, ikanago requested changes

2022-06-14 05:03 UTC, ikanago commented on skqulacs/circuit/circuit.py
> +        share_with_coef: Optional[float] = None,
実装を見ると `share_with` が `None` のときは `share_with_coef` が無視されているので，それについても言及した方がいいと思います．

2022-06-21 02:04 UTC, forest1040 commented on skqulacs/circuit/circuit.py
> +        self.coef = coef
ありがとうございます。 `__init__()`削除しました。

2022-06-21 04:15 UTC, ikanago approved these changes
LGTM です!

2022-06-21 04:52 UTC, merged