102 qcnn
Qulacs-Osaka/scikit-qulacs pull request #210
Opened 2022-06-28 05:33 UTC by forest1040

2022-06-28 05:38 UTC, forest1040 commented
@ikanago レビューをお願いします！

2022-07-05 06:28 UTC, ikanago requested changes
遅くなりました 🙏 
僕の確認した限りでは TensorFlow Quantum のドキュメントと同じ回路になっていました．
細かい点コメントしたのでお願いします．

2022-07-05 06:28 UTC, ikanago commented on skqulacs/circuit/pre_defined.py
> +    # circuit = pooling_circuit(circuit, 3, 7)
このコメントアウトは削除しておいたほうが見やすそうです．

2022-07-05 06:28 UTC, ikanago commented on skqulacs/circuit/pre_defined.py
> +    def tree(ns):
`tree` の動作は非自明なので動作例があると分かりやすいと思います．

2022-07-06 09:14 UTC, forest1040 commented on skqulacs/circuit/pre_defined.py
> +    def tree(ns):
コメントを追加しました！

2022-07-06 09:15 UTC, forest1040 commented
@ikanago 修正しました。再確認をお願いします！

2022-07-08 04:10 UTC, ikanago approved these changes
1ヶ所修正の提案をしましたが LGTM です!

2022-07-08 04:10 UTC, ikanago commented on skqulacs/circuit/pre_defined.py
> +    # 次の階層の[1, 3],[5, 7]となります。階層の数字は下の層の番号が大きい方通しがペアになります。
意味が通らなさそうだったんですが、こうですかね?
```suggestion
    # 次の階層の[1, 3],[5, 7]となります。階層の数字は下の層の通し番号が大きい方がペアになります。
```

2022-07-12 00:37 UTC, merged