Manyclass
Qulacs-Osaka/scikit-qulacs pull request #234
Opened 2022-09-22 07:02 UTC by WATLE

2022-09-22 07:02 UTC, WATLE commented
#223

2022-09-27 04:37 UTC, ikanago requested changes

2022-09-27 04:37 UTC, ikanago commented on dqn_cl_test.py
> +for depth in range(3, 10):
このファイルはプロジェクトルートにあると不自然なので，テストに入れたほうがいいと思います．
実行に時間がかかるようならスキップすればよさそうです．

2022-09-27 04:37 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +            self.fitting_qubit += 1
そんなにパフォーマンスは変わらないと思いますが、log で直接計算したほうが理解しやすそうです．

2022-09-27 04:37 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +        self.fitting_qubit = 1
`fitting_qubit` も↑の dataclass のメンバ定義に書いておいてください 🙏

2022-10-06 06:33 UTC, WATLE commented on dqn_cl_test.py
> +for depth in range(3, 10):
これそもそそ別ブランチにあるはずのファイルでした。なぜここに... ? 消しました

2022-10-06 06:38 UTC, WATLE commented on skqulacs/qnn/classifier.py
> +            self.fitting_qubit += 1
小数点誤差を気にしていましたが、うまく処理しました

2022-10-07 07:33 UTC, ikanago requested changes

2022-10-07 07:33 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +        self.fitting_qubit = math.ceil(math.log2(self.num_class - 0.001))
`self.num_class` がちょうど2べきのときに1少なくなるから 0.001 引いてるんだと思うんですが、floor して1足すほうがわかりやすいかなと思いました:
```python
int(math.floor(math.log2(self.num_class))) + 1
```

2022-10-07 07:33 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +    fitting_qubit: int = field(init=False)
👍

2022-10-20 09:43 UTC, WATLE commented on skqulacs/qnn/classifier.py
> +        self.fitting_qubit = math.ceil(math.log2(self.num_class - 0.001))
小数点誤差を気にしています

2022-10-25 04:34 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +        self.fitting_qubit = math.ceil(math.log2(self.num_class - 0.001))
`math.log2(self.num_class)` が誤差でわずかに小さくなって，それを `math.floor` すると 1 小さくなりうるということですか?

2022-10-27 06:27 UTC, WATLE commented on skqulacs/qnn/classifier.py
> +        self.fitting_qubit = math.ceil(math.log2(self.num_class - 0.001))
yes

2022-10-27 07:38 UTC, forest1040 approved these changes
ありがとうございます。LGTMです！

2022-10-27 07:39 UTC, merged