regのバグ修正
Qulacs-Osaka/scikit-qulacs pull request #67
Opened 2021-08-31 11:03 UTC by WATLE

regの部分、割と明らかにバグってたけど、直すとloss増える...

2021-09-01 04:57 UTC, ikanago requested changes
これからこんな感じでプルリクエストのたびに誰かがレビューをしようと思うのでよろしくお願いします 🙏 
参考: #65

2021-09-01 04:57 UTC, ikanago commented on skqulacs/qnn/regressor.py
> +        minimum -= sa * 0.4
この0.4や1.4などの係数を決めるのに参考にした資料などはありますか?
なければ「こうすると現状はいい感じになる」みたいなことを書いておいてください

2021-09-01 04:58 UTC, ikanago commented
loss は大幅に増えているわけではなさそうなので個人的には問題ないと思います

2021-11-12 01:08 UTC, kosukemtr commented
かなり古いので一旦閉じます

2021-11-12 01:08 UTC, closed without merging