Merge backporp implementation to main
Qulacs-Osaka/scikit-qulacs pull request #92
Opened 2021-11-10 05:34 UTC by kosukemtr

2021-11-10 05:43 UTC, kosukemtr commented
とりあえず main の変更を取り込んだので、次 CI を qulacs-osaka でできるようにします

2021-11-10 08:25 UTC, kosukemtr commented
できなかったので ikanago くんに託します

2021-11-11 05:49 UTC, ikanago commented on aaa.py
> +
手元でのテスト用なら消しておいてください 🙏  (パッと見すでにあるテストと同じなので不要そうです)

2021-11-11 06:36 UTC, ikanago requested changes
いくつか変更のリクエストを書きました．
あと，`create_farhi_watle` のテストがなかったので追加をお願いします 🙇

2021-11-11 06:36 UTC, ikanago commented on skqulacs/circuit/pre_defined.py
> +        sban = index // len(x)
変数名が何を表しているかが非自明なので，多少長くなっても説明的な名前の方がいいと思います

2021-11-11 06:36 UTC, ikanago commented on skqulacs/circuit/pre_defined.py
> +        sban = index // len(x)
たとえば `inkaz` は `qubits_p_bit` とすれば行末のコメントがなくても意味が分かりそうです

2021-11-11 06:36 UTC, ikanago commented on skqulacs/circuit/pre_defined.py
> +nCr = np.zeros([15, 15])
定数でないグローバル変数はややこしいので関数に切り出した方がいいです．
たとえば `nCr` は
```python
def combination(size: int) -> np.array:
    nCr = np.zeros([size, size])
    # 90~92行目の初期化処理
    return nCr
```
として `nCr = combination(15)` とできます．`nCr` を使い回すようになるまではこれでいいと思います．
使い回す必要が出てきたときは，使う関数に引数で渡すようにすればよさそうです．

2021-11-11 06:36 UTC, ikanago commented on skqulacs/circuit/pre_defined.py
> +                    ] * ((-1) ** (i + j + k))
上述の通り，関数に切り出します

2021-11-11 06:36 UTC, ikanago commented on skqulacs/qnn/classifier.py
> +        """
コメントアウトは削除しておいてください 🙏

2021-11-11 06:36 UTC, ikanago commented on skqulacs/qnn/regressor.py
> +        """
このコメントも削除しておいてください

2021-11-11 06:36 UTC, ikanago commented on skqulacs/circuit/circuit.py
> +                if not parameter.is_input():
`if parameter.is_learning_parameter() and not parameter.is_input():` としたほうがネストが浅くなって見やすそうです

2021-11-11 06:36 UTC, ikanago commented on skqulacs/circuit/circuit.py
> +        run. but x is not changed form prev run.
form -> from のタイポです

2021-11-11 06:36 UTC, ikanago commented on skqulacs/circuit/circuit.py
> +        for parameter in self._parameter_list:
ここは `run()` と重複しているので，今はこのままにして今度直しましょう

2021-11-12 10:20 UTC, WATLE commented on skqulacs/circuit/pre_defined.py
> +nCr = np.zeros([15, 15])
preprocess_x が呼び出されるたびにnCrを計算しなくて済みますか？

2021-11-12 10:58 UTC, kotamanegi reviewed
外部から失礼します。
ちょっと気になった部分を列挙してみました。

2021-11-12 10:58 UTC, kotamanegi commented on skqulacs/circuit/pre_defined.py
> +            print("bug")
こういうエラー処理は例外を投げて、エラーが発生したことを標準出力への出力以外で明示した方が良いと思います。[参考文献](https://docs.python.org/ja/3/tutorial/errors.html)
```suggestion
            raise RuntimeError("bug")
```

2021-11-12 10:58 UTC, kotamanegi commented on skqulacs/circuit/pre_defined.py
> +            xb = xa  # あきらめた
実装をあきらめたという意味の場合は、NotImplementedErrorを使って実装されてないということを明示するのが良いと思います。
```suggestion
            raise NotImplementedError("実装をあきらめた")
```

2021-11-12 10:58 UTC, kotamanegi commented on skqulacs/circuit/pre_defined.py
> +nCr = np.zeros([15, 15])
`preprocess_x`の引数にnCrの値を入れておくことで、使いまわしをすることができます。
nCrの方はcreate_farhi_watle()関数の中で定義することで、グローバル変数にしないで良くなります。

2021-11-12 11:00 UTC, WATLE commented on skqulacs/circuit/pre_defined.py
> +            xb = xa  # あきらめた
nCrをあきらめてはいるけど、そのときはNotImplementedErrorじゃなくて通常版を返したい

2021-11-12 11:07 UTC, kotamanegi commented on skqulacs/circuit/pre_defined.py
> +            xb = xa  # あきらめた
それはこのコードから読み取りづらいので、コメントとして追加しておきたいです。
```
            xb = xa # 実装が困難であるため、通常版を返す
```

2021-11-12 11:30 UTC, merged